sudo: required

language: bash
services:
  - docker

branches:
  only:
  - master

env:
   global:
    - COMMIT=${TRAVIS_COMMIT::8}
   matrix: 
    - VARIANT=httpie
    - VARIANT=boom
    - VARIANT=serverless
    - VARIANT=kubectl

before_script:
  - env | sort
  - cd "$VARIANT"
  - IMAGE="melvinlee/docker-util:${VARIANT}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
        docker build -t "$IMAGE" .
    )
  
after_script:
  - docker images

after_success:
  - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
  - docker push $IMAGE